# Nixpkgs-style build for the LogicAnalyzer software suite.
#
# The NuGet lock file lives in ./deps.json and is regenerated by running
#
#     $(nix-build -A logicanalyzer.fetch-deps --no-out-link) ./deps.json
#
# after any change to *.csproj or NuGet package versions.
{
  lib,
  buildDotnetModule,
  dotnetCorePackages,
  copyDesktopItems,
  makeDesktopItem,
  fontconfig,
  icu,
  libICE,
  libSM,
  libX11,
  libXcursor,
  libXext,
  libXi,
  libXrandr,
  libXrender,
  libXtst,
  libglvnd,
  libkrb5,
  openssl,
  python3,
  stdenv,
  zlib,
}:

buildDotnetModule (finalAttrs: {
  pname = "logicanalyzer";
  version = "6.0.0.1";

  src = lib.cleanSource ./.;

  # Publish the three entry-point projects individually. Passing the .sln
  # instead makes `dotnet publish` schedule SharedDriver in parallel across
  # all referents, racing on its intermediate deps.json output.
  projectFile = [
    "Software/LogicAnalyzer/LogicAnalyzer/LogicAnalyzer.csproj"
    "Software/LogicAnalyzer/CLCapture/CLCapture.csproj"
    "Software/LogicAnalyzer/TerminalCapture/TerminalCapture.csproj"
  ];
  executables = [
    "LogicAnalyzer"
    "CLCapture"
    "TerminalCapture"
  ];

  nugetDeps = ./deps.json;

  dotnet-sdk = dotnetCorePackages.sdk_8_0;
  dotnet-runtime = dotnetCorePackages.runtime_8_0;

  # Framework-dependent publish; the .NET runtime is provided by Nix via the
  # wrapper, overriding <SelfContained>true</SelfContained> in the .pubxml
  # profiles (which target the upstream zip distribution, not Nix).
  selfContainedBuild = false;

  nativeBuildInputs = [ copyDesktopItems ];

  postPatch = ''
    # The decoder bridge unconditionally overwrites decoders/sigrokdecode.py
    # at startup; upstream already ships that file in the decoders tree and
    # the Nix store is read-only, so the write throws and takes down the
    # whole Python-init path. Skip the write when the target already exists.
    substituteInPlace \
      Software/LogicAnalyzer/LogicAnalyzer/SigrokDecoderBridge/SigrokPythonEngine.cs \
      --replace-fail \
        'using var output = File.Create(Path.Combine(DecoderPath, "sigrokdecode.py"));' \
        'using var output = File.Exists(Path.Combine(DecoderPath, "sigrokdecode.py")) ? Stream.Null : File.Create(Path.Combine(DecoderPath, "sigrokdecode.py"));'
  '';

  # Native libs loaded at runtime by Avalonia (X11 + GL + Skia/HarfBuzz from
  # NuGet), the .NET runtime (ICU, OpenSSL, zlib, Kerberos), and pythonnet.
  runtimeDeps = [
    fontconfig
    icu
    libICE
    libSM
    libX11
    libXcursor
    libXext
    libXi
    libXrandr
    libXrender
    libXtst
    libglvnd
    libkrb5
    openssl
    python3
    stdenv.cc.cc.lib
    zlib
  ];

  # The app resolves libpython by reading python.cfg next to the assembly,
  # falling back to spawning python3 from PATH. We pin the Nix-provided
  # libpython via postInstall so no PATH lookup is ever attempted; keeping
  # python3 in runtimeDeps above also exposes it on LD_LIBRARY_PATH for
  # any transitive dlopen.

  desktopItems = [
    (makeDesktopItem {
      name = "logicanalyzer";
      exec = "LogicAnalyzer";
      icon = "logicanalyzer";
      desktopName = "LogicAnalyzer";
      genericName = "Logic Analyzer";
      comment = "Pi Pico based logic analyzer with Sigrok decoder support";
      categories = [
        "Development"
        "Electronics"
      ];
    })
  ];

  postInstall = ''
    install -Dm644 Software/LogicAnalyzer/LogicAnalyzer/Assets/Logo.png \
      $out/share/icons/hicolor/512x512/apps/logicanalyzer.png

    printf '%s' '${python3}/lib/libpython${lib.versions.majorMinor python3.version}.so' \
      > $out/lib/logicanalyzer/python.cfg
  '';

  meta = {
    description = "Pi Pico based logic analyzer with Sigrok decoder support";
    homepage = "https://github.com/gusmanb/logicanalyzer";
    license = lib.licenses.gpl3Only;
    mainProgram = "LogicAnalyzer";
    platforms = [
      "x86_64-linux"
      "aarch64-linux"
    ];
  };
})
